# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [113]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: pandas in c:\users\nabil\appdata\roaming\python\python39\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\program files\python39\lib\site-packages (1.24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python39\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nabil\appdata\roaming\python\python39\site-packages (from pandas) (2025.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\nabil\appdata\roaming\python\python39\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\program files\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [114]:
# Import here.

import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [115]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [116]:
# Count by hand. (lol kidding)

df_food.shape

(125, 61)

In [117]:
# Try to print or display it nicely.
print(f"Number of rows: {df_food.shape[0]}", " and "  , f"Number of columns: {df_food.shape[1]}")

Number of rows: 125  and  Number of columns: 61

What are the columns and their types in this data set?

In [118]:
# Show the column names and their types.
df_food.dtypes

GPA                              object
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                     object
comfort_food_reasons             object
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                     object
diet_current_coded                int64
drink                           float64
eating_changes                   object
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                object
fav_cuisine                      object
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                   object
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                     object
ideal_diet                       object
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend              object
mother_education                float64
mother_profession                object
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                      object
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                           object
dtype: object

In [119]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
df_food.info() # This is a method that prints the information to the console. It does not return a DataFrame.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [120]:
# Remove ‘em.
# .copy() creates an independent DataFrame in memory.
df_food_col_subset = df_food[["calories_day", "weight", "Gender"]].copy()

In [121]:
# Is there a second way to remove columns? # ( , "all other columns ..." )
df_food_col_subset = df_food.drop(columns=["GPA", "breakfast", "coffee"])

In [122]:
# 🚀 Extra credit: What about a third way to remove columns?

keep_cols = ["calories_day", "weight", "Gender"]
# Drop all columns that are NOT in keep_cols
df_food_col_subset = df_food.drop(columns=df_food.columns.difference(keep_cols))

What about `NaN`s? How many are there?

In [123]:
# Count ‘em.
df_food_col_subset.isna().sum().sum()

21

In [124]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_food_col_subset.isna().sum()

Gender           0
calories_day    19
weight           2
dtype: int64

In [125]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.
df_food_col_subset \
      .isna()\
      .sum()

Gender           0
calories_day    19
weight           2
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [126]:
# Drop ‘em in-place.
df_food_col_subset = df_food_col_subset.dropna()

df_food_col_subset.isna().sum().sum()

0

In [127]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

df_food.isna().sum().sum()

149

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [128]:
# Fix that in-place.
df_food_col_subset["weight"] = pd.to_numeric(df_food_col_subset["weight"])
df_food_col_subset["calories_day"] = pd.to_numeric(df_food_col_subset["calories_day"])
df_food_col_subset = df_food_col_subset.dropna()
print(df_food_col_subset.head())
print(df_food_col_subset.dtypes)

ValueError: Unable to parse string "I'm not answering this. " at position 1

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [ ]:
# Savey save!
df_food_col_subset.to_csv("cleaned_food_data.csv", index=False)

In [ ]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
with open("cleaned_food_data.csv", "r") as file:
    for i in range(5):
        print(file.readline(), end="")

Gender,calories_day,weight
1,3.0,155.0
1,2.0,190.0
1,3.0,190.0
2,3.0,180.0

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [ ]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', delimiter='\t')

Was that hard? 🙃 yes

### Explore

You know the drill.

How much data did you just load?

In [ ]:
# Count by hand. I’m dead serious.
print(f"Number of rows: {df_salary.shape[0]}", " and "  , f"Number of columns: {df_salary.shape[1]}")

Number of rows: 28062  and  Number of columns: 18

What are the columns and their types?

In [ ]:
# Show the column names and their types.

df_salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  object
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  object
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  object
 3   Job title                                                                                                                                                                                                                             28061 non-null  object
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   object
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  object
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  object
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    object
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   object
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  object
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  object
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  object
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  object
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  object
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  object
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  object
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  object
dtypes: float64(1), object(17)
memory usage: 3.9+ MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [ ]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
new_columns = [
    "timestamp",
    "age",
    "industry",
    "title",
    "title_context",
    "salary",
    "additional_compensation",
    "currency",
    "other_currency",
    "salary_context",
    "country",
    "state",
    "city",
    "total_yoe",
    "field_yoe",
    "highest_education_completed",
    "gender",
    "race",
]

df_salary.columns = new_columns

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [ ]:
# List the unique industries and a count of their instances.
# Unique industries and their counts (excluding missing values)
industry_counts = df_salary["industry"].value_counts()
industry_counts

industry
Computing or Tech                          4699
Education (Higher Education)               2464
Nonprofits                                 2419
Health care                                1896
Government and Public Administration       1889
                                           ...
Gaming (Gambling)                             1
Regulatory Affairs- nutraceuticals            1
Manufacturing : corporate admin support       1
Real Estate Investment Support                1
Wine & Spirits                                1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [ ]:
# Filtery filter.

industry_counts.head()

industry
Computing or Tech                       4699
Education (Higher Education)            2464
Nonprofits                              2419
Health care                             1896
Government and Public Administration    1889
Name: count, dtype: int64

Do a sanity check by counting.

In [ ]:
# Sanity check count.
print((df_salary["industry"] == "Computing or Tech").sum())
print((df_salary["industry"] == "Education (Higher Education)").sum())
print((df_salary["industry"] == "Nonprofits").sum())
print((df_salary["industry"] == "Health care").sum())
print((df_salary["industry"] == "Government and Public Administration").sum())

4699
2464
2419
1896
1889

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [ ]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary = df_salary[df_salary["currency"] == "USD"]
df_salary["currency"]

0        USD
2        USD
3        USD
4        USD
5        USD
        ...
28052    USD
28057    USD
28058    USD
28059    USD
28060    USD
Name: currency, Length: 23374, dtype: object

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [ ]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary["country"].value_counts()

country
United States                                8989
USA                                          7922
US                                           2606
United States                                 667
U.S.                                          580
                                             ...
Cote d'Ivoire                                   1
From Romania, but for an US based company       1
Somalia                                         1
Norway                                          1
Burma                                           1
Name: count, Length: 229, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [ ]:
# Replace them all in-place with 'US'.

top_5 = df_salary["country"].value_counts().head().index

# 2. Replace all 5 variations with 'US'
df_salary["country"] = df_salary["country"].replace(top_5, "US")

Have a look at the count of each unique country again now.

In [ ]:
# Count again.
df_salary["country"].value_counts()

country
US               22314
usa                183
united states      116
Us                 105
U.S.A.              45
                 ...
Cuba                 1
Cote d'Ivoire        1
Somalia              1
Norway               1
Burma                1
Name: count, Length: 221, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

# 1. Lowercase and strip spaces, dots, and numbers from the ends
clean_country = df_salary["country"].astype(str).str.lower().str.strip(" .0123456789")

# 2. Define simple, clean target strings
us_terms = [
    "us", 
    "usa", 
    "u.s", 
    "u.s.a", 
    "united states", 
    "united states of america", 
    "america"
]

# 3. Update the country column to 'US' for all matching rows
df_salary.loc[clean_country.isin(us_terms), "country"] = "US"

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
df_salary["country"].value_counts()

country
US                        23063
Canada                       16
Australia                     8
The United States             7
Israel                        7
                          ...
Bangladesh                    1
Cambodia                      1
Hong Kong                     1
Japan, US Gov position        1
Burma                         1
Name: count, Length: 176, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [ ]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_us_states = df_salary[(df_salary["country"] == "US")]
state_salaries = (
    df_us_states.groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values(by="mean", ascending=False)
)
state_salaries

,min,mean,max
state,,,
"Michigan, Texas, Washington",340000,340000.000000,340000
"Indiana, Ohio",245000,245000.000000,245000
Alaska,27040,232275.078125,10000000
"Colorado, Nevada",190000,190000.000000,190000
"California, Texas",185000,185000.000000,185000
...,...,...,...
"District of Columbia, Washington",35000,35000.000000,35000
"Delaware, Pennsylvania",35000,35000.000000,35000
"Alabama, California",29120,29120.000000,29120
"District of Columbia, Maryland, Pennsylvania, Virginia",27040,27040.000000,27040
"Maryland, New York",14000,14000.000000,14000

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [ ]:
# Fix it in-place.
df_salary["salary"] = df_salary["salary"].astype(str).str.replace(",", "").str.replace("$", "").str.strip()
df_salary["salary"] = pd.to_numeric(df_salary["salary"])

Let’s try that again.

In [ ]:
# Try it again. Yeah!

df_us_states = df_salary[(df_salary["country"] == "US")]
state_salaries = (
    df_us_states.groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values(by="mean", ascending=False)
)
state_salaries

,min,mean,max
state,,,
"Michigan, Texas, Washington",340000,340000.000000,340000
"Indiana, Ohio",245000,245000.000000,245000
Alaska,27040,232275.078125,10000000
"Colorado, Nevada",190000,190000.000000,190000
"California, Texas",185000,185000.000000,185000
...,...,...,...
"District of Columbia, Washington",35000,35000.000000,35000
"Delaware, Pennsylvania",35000,35000.000000,35000
"Alabama, California",29120,29120.000000,29120
"District of Columbia, Maryland, Pennsylvania, Virginia",27040,27040.000000,27040
"Maryland, New York",14000,14000.000000,14000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [129]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary["timestamp"] = pd.to_datetime(df_salary["timestamp"], errors="coerce")

df_2021_2023 = df_salary[df_salary["timestamp"].dt.year.isin([2021, 2022, 2023])].copy()

df_us_states_filtered = df_2021_2023[(df_2021_2023["country"] == "US")]

state_salaries_2021_2023 = (
    df_us_states_filtered.groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values(by="mean", ascending=False)
)
state_salaries_2021_2023

                                                       min      mean     max
state
Michigan, Texas, Washington                         340000  340000.0  340000
Indiana, Ohio                                       245000  245000.0  245000
Colorado, Nevada                                    190000  190000.0  190000
California, Texas                                   185000  185000.0  185000
California, Montana                                 185000  185000.0  185000
...                                                    ...       ...     ...
District of Columbia, Washington                     35000   35000.0   35000
Delaware, Pennsylvania                               35000   35000.0   35000
Alabama, California                                  29120   29120.0   29120
District of Columbia, Maryland, Pennsylvania, V...   27040   27040.0   27040
Maryland, New York                                   14000   14000.0   14000

[131 rows x 3 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)